[package]
name = "symdep"
version = "0.1.0"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
edition = "2021"

[dependencies]
goblin = "0.4"
clap = { version = "3.0", features = ["derive"] }
msvc-demangler = "0.9"
cpp_demangle = "0.3"
rustc-demangle = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
