[package]
name = "symdep"
version = "0.1.1"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
edition = "2021"
description = "Command line tool to show the imports and exports of binaries."
repository = "https://github.com/Berrysoft/symdep"
license = "MIT"

[dependencies]
goblin = "0.9.1"
clap = { version = "4.0", features = ["derive"] }
msvc-demangler = "0.10"
cpp_demangle = "0.4"
rustc-demangle = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
